import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <a href="/">HOME</a> |<a href="/about">ABOUT</a> |
        <a href="/contact">CONTACT</a>
        <hr />
        {children}
      </body>
    </html>
  );
}
